// src/vue/Station.vue
<template>
	<a
		:href="url"
		:data-id="id"
		:data-format="format"
		:data-city="city"
		:data-state="state"
		:data-freq="freq"
		:data-calls="calls"
		:data-band="band"
		target="_blank"
		rel="noopener"
	>
		<StationLogo v-if="image.length"
			:src="image.replace('http://', '//')"
			:alt="'Logo for ' + id"
		/>
		<h3>{{ id }}</h3>
		<div class="crsg-sf-locale">{{ city }}, {{ state }}</div>
		<div class="crsg-sf-details">{{ freq }}</div>
		<div class="crsg-sf-details">{{ calls }} {{ band }}</div>
		<div class="crsg-sf-details">{{ format }}</div>
	</a>
</template>

<script>
import StationLogo from './StationLogo.vue'
export default {
	name: 'Station',
	components: { StationLogo },
	props: {
		url: null,
		id: null,
		format: null,
		city: null,
		state: null,
		freq: null,
		calls: null,
		band: null,
		image: null
	}
}
</script>

// src/preact/Station.jsx
import { h, Component } from 'preact';
import { ViewportObserver } from "preact-intersection-observer";

export default class Station extends Component {
	constructor() {
		super();
	}
	render(props) {
		let Tag = 'div',
			attribs = {};
		if (props?.url?.length) {
			Tag = 'a';
			attribs = {
				href: props.url,
				target: "_blank",
				rel: "noopener"
			};
		}
		return (
			<Tag {...attribs}>
				{props?.image && (
					<ViewportObserver
						as="figure"
						render={({ inView, entry }) => {
							if (inView) {
								return (
									<img
										src={props.image.replace('http://', 'https://')}
										alt={`Logo for ${props.id}`}
									/>
								);
							}
							return null;
						}}
					/>
				)}
				<h3>{props.id}</h3>
				<div className="crsg-sf-locale">{props?.city}, {props?.state}</div>
				{props?.freq && <div className="crsg-sf-details">{props.freq}</div>}
				{props?.calls && <div className="crsg-sf-details">{props.calls} {props?.band}</div>}
				{props?.format && <div className="crsg-sf-details">{props.format}</div>}
			</Tag>
		)
	}
}
