// src/vue/StationFinder.vue
<template>
	<div class="crsg-stationfinder">
		<ul class="crsg-sf-filters">
			<li class="crsg-sf-states">
				<label for="stations-states">
					Market State:
				</label>
				<select v-model="filters.state" id="stations-states" @change="selectState">
					<option value="all" selected="selected" v-if="filters.state == 'all'">All</option>
					<option value="all" v-else>All</option>
					<option v-for="state in states" :value="state.abbr">{{ state.name }}</option>
				</select>
			</li>
			<li class="crsg-sf-cities">
				<label for="stations-cities">
					Market City:
				</label>
				<select v-model="filters.city" id="stations-cities" @change="selectCity">
					<option value="all" selected="selected" v-if="filters.city == 'all'">All</option>
					<option value="all" v-else>All</option>
					<option v-for="city in filteredCities" :value="city">{{ city.name }}</option>
				</select>
			</li>
			<li class="crsg-sf-formats">
				<label for="stations-formats">
					Formats:
				</label>
				<select v-model="filters.format" id="stations-formats">
					<option value="all" selected="selected" v-if="filters.format == 'all'">All</option>
					<option value="all" v-else>All</option>
					<option v-for="format in filteredFormats" :value="format">{{ format }}</option>
				</select>
			</li>
			<li class="crsg-sf-search">
				<label for="stations-search">
					Search:
				</label>
				<input id="stations-search" type="text" placeholder="Search..." v-on:keyup="debounceQuery" :value="filters.query" aria-label="Search">
				<button v-on:click="filters.query = ''" aria-label="Clear Search">Clear</button>
			</li>
		</ul>
		<ul v-if="filteredStations?.length" class="crsg-sf-stations">
			<li v-for="station in filteredStations">
				<Station v-bind="station" />
			</li>
		</ul>
		<ul v-else class="crsg-sf-stations ">
			<li>No stations found.</li>
		</ul>
	</div>
</template>

<script>
import { debounce, sortBy } from 'lodash-es'
import { APISettings } from './config.js'
import { stateNames } from './statenames.js'
import Station from './Station.vue'

const union = (arr, ...args) => [...new Set(arr.concat(...args))];

export default {
	name: 'StationFinder',
	components: { Station },
	data() {
		return {
			stations: [],
			states: {},
			filters: {
				state: 'all',
				city: 'all',
				format: 'all',
				query: '',
			}
		}
	},
	methods: {
		debounceQuery: debounce(function (e) {
			this.filters.query = e.target.value;
		}, 200),
		getFilteredStates() {
			if (!this.states?.length) {
				return [];
			}

			const props = this;
			return props.states.filter(state => {
				let found = true;
				if (
					props.filters.state !== 'all'
					&& props.filters.state !== state.abbr
				) {
					found = false;
				}
				if (
					props.filters.city !== 'all'
					&& props.filters.state !== state.abbr
				) {
					found = false;
				}
				if (
					props.filters.format !== 'all'
					&& ! state.formats.includes(props.filters.format)
				) {
					found = false;
				}

				if (found) {
					return state;
				}
			}).flat()
		},
		selectCity() {
			if (this.filters.city !== 'all') {
				this.filters.state = this.filters.city.state;
			}
		},
		selectState() {
			// reset selected city if current city is not in current state
			if (
				this.filters.city !== 'all'
				&& this.filters.city.state
				&& this.filters.city.state !== this.filters.state
			) {
				this.filters.city = 'all';
			}

			// reset selected format if there are no stations in
			// the selected state with that format
			if (
				this.filters.format !== 'all'
				&& this.filteredFormats.length < 1
			) {
				this.filters.format = 'all'
			}
		}
	},
	computed: {
		filteredStates() {
			const states = this.getFilteredStates();
			if (states.length === 1) {
				this.filters.state = states[0].abbr;
			}
			return states;
		},
		filteredCities() {
			const states = this.getFilteredStates(),
				cities = [];

			states.forEach(state => {
				state.cities.forEach(city => {
					cities.push({
						state: state.abbr,
						name: city
					});
				});
			});

			if (cities.length === 1) {
				this.filters.city = cities[0];
			}
			return sortBy(cities, ['name']);
		},
		filteredFormats() {
			if (this.filters.state === 'all') {
				if (!this.states?.length) {
					return;
				}
				return [
					...new Set(
						this.states.map(n => n.formats).flat()
					)
				];
			}

			const states = this.getFilteredStates(),
				formats = new Set(
					states.map(n => n.formats).flat()
				);

			if (formats.length === 1) {
				this.filters.format = formats[0];
			}

			return [...formats].sort()
		},
		filteredStations() {
			const props = this;

			if (!this.stations?.length) {
				return;
			}
			const stations = this.stations.filter(station => {
				if (
					props.filters.state !== 'all'
					&& props.filters.state !== station.state
				) {
					return;
				}
				if (
					props.filters.city !== 'all'
					&& props.filters.city.name !== station.city
				) {
					return;
				}
				if (
					props.filters.format !== 'all'
					&& props.filters.format !== station.format
				) {
					return;
				}
				if (props.filters.query?.length) {
					const searchable = [
						station.id,
						station.format,
						station.freq,
						station.calls,
						station.band,
						station.city,
						station.state
					].map(v => v.toLowerCase());
					if (
						!searchable.filter(v => {
							return v.indexOf(props.filters.query.toLowerCase()) > -1
						})?.length
					) {
						return;
					};
				}
				return station;
			});

			sortBy(stations, ['city', 'state', 'id']);
			return stations;
		}
	},
	created() {
		const props = this;
		return fetch(
			APISettings.baseURL,
			{
				method: 'GET',
				headers: APISettings.headers
			}
		).then(response => {
			if (response.status !== 200) {
				throw response.status;
			}
			response.json().then(data => {
				props.stations = data;

				const states = {};
				props.stations.forEach(station => {
					if (states.hasOwnProperty(station.state)) {
						states[station.state].cities = union(
							states[station.state].cities,
							[station.city]
						);
						states[station.state].formats = union(
							states[station.state].formats,
							[station.format]
						);
						return;
					}
					states[station.state] = {
						abbr: station.state,
						name: stateNames[station.state],
						cities: [station.city],
						formats: [station.format]
					};
				});

				const sortedStates = sortBy(states, 'name');
				sortedStates.forEach(state => {
					state.cities = state.cities.sort();
					state.formats = state.formats.sort();
				});
				props.states = sortedStates;
			});
		});
	}
}
</script>

// src/preact/StationFinder.jsx
import { h, Component } from 'preact';
import { useState, useMemo } from "preact/hooks";

import { debounce, sortBy } from 'lodash-es'
import config from './config';
import stateNames from './statenames';
import Station from './Station';

const union = (arr, ...args) => [...new Set(arr.concat(...args))];

export default class StationFinder extends Component {
	constructor() {
		super();
		this.state = {
			loading: false,
			stations: [],
			status: 'Loading...'
		}
	}

	componentDidMount() {
		this.setState({ loading: true, status: 'Loading...' });
		fetch(
			config.baseURL, { method: 'GET', headers: config.headers }
		).then(resp => {
			if (resp.status !== 200) {
				this.setState({ status: 'Failed to load stations! Please try again later.' });
				throw Response.status;
			}
			resp.json().then(data => {
				this.setState({ stations: data });
				this.setState({ loading: false });
			})
		}).catch(resp => {
			this.setState({ status: 'Failed to load stations! Please try again later. ' + (resp.reason ? resp.reason : '') });
		});
	}

	render(props, state) {
		if (state.loading) {
			return (
				<div>{state.status}</div>
			);
		}

		const [filters, setFilters] = useState({
			city: 'all',
			state: 'all',
			format: 'all',
			query: ''
		});
		const changeStateFilter = (e) => {
			const newFilters = { ...filters, state: e.target.value, city: 'all' };
			setFilters(newFilters);
		};
		const changeCityFilter = e => {
			const v = e.target.value;
			if (v == 'all') {
				setFilters({ ...filters, city: 'all' });
				return;
			}

			const s = v.substring(0, 2);
			setFilters({ ...filters, state: s, city: v });
		}
		const changeFormatFilter = e => {
			setFilters({ ...filters, format: e.target.value });
		}
		const clearQuery = e => {
			setFilters({ ...filters, query: '' });
		}

		const debounceQuery = debounce(e => {
			setFilters({ ...filters, query: e.target.value });
		}, 200);

		const relevantStations = useMemo(() => {
			const stations = state.stations.filter(station => {
				let found = true;
				if (filters.state !== 'all' && station.state !== filters.state) {
					found = false;
				}
				if (filters.city !== 'all' && station.city !== filters.city.substring(3)) {
					found = false;
				}
				if (filters.format !== 'all' && station.format !== filters.format) {
					found = false;
				}
				return found;
			});
			return stations;
		}, [state.stations, filters.state, filters.city, filters.format]);

		const filteredData = useMemo(() => {
			const stations = relevantStations;
			const states = {},
				cities = {},
				formats = {};

			stations.forEach(station => {
				if (!stateNames?.[station.state]) {
					console.warn('Station found with no full state', station);
					return;
				}
				states[station.state] = {
					abbr: station.state,
					name: stateNames[station.state]
				};
				const key = `${station.state}|${station.city}`;
				cities[key] = {
					key: key,
					state: station.state,
					name: station.city,
				};
				formats[station.format] = station.format;
			});

			const sortedStates = sortBy(Object.values(states), ['name']);
			const sortedCities = sortBy(Object.values(cities), ['name']);
			const sortedFormats = Object.values(formats).sort();

			const newFilters = { ...filters }
			if (sortedStates.length === 1) {
				newFilters.state = sortedStates[0].abbr;
			}
			if (sortedCities.length === 1) {
				newFilters.city = sortedCities[0].key;
			}
			if (sortedFormats.length === 1) {
				newFilters.format = sortedFormats[0];
			}
			setFilters(newFilters);

			return {
				states: sortedStates,
				cities: sortedCities,
				formats: sortedFormats
			}
		}, [relevantStations]);

		// Generate filtered stations
		const filteredStations = useMemo(() => {
			const stations = relevantStations.filter(station => {
				if (filters.query.length) {
					const searchable = [
						station.id, station.format, station.freq,
						station.calls, station.band, station.city, station.state
					].map(v => v.toLowerCase());
					if (
						!searchable.filter(v => {
							return v.includes(filters.query.toLowerCase());
						})?.length
					) {
						return;
					}
				}
				return station;
			});

			return sortBy(stations, ['city', 'state', 'id']);
		}, [relevantStations, filters.query]);

		return (
			<div className="crsg-stationfinder">
				<ul className="crsg-sf-filters">
					<li className="crsg-sf-states">
						<label for="stations-states">
							Market State:
						</label>
						<select
							name="state"
							id="stations-states"
							value={filters.state}
							onChange={changeStateFilter}
						>
							<option key="all" value="all">All</option>
							{filteredData.states.map(s => (
								<option key={s.abbr} value={s.abbr}>{s.name}</option>
							))}
						</select>
					</li>
					<li className="crsg-sf-cities">
						<label for="stations-cities">
							City:
						</label>
						<select
							name="city"
							id="stations-cities"
							value={filters.city}
							onChange={changeCityFilter}
						>
							<option key="all" value="all">All</option>
							{filteredData.cities.map(c => (
								<option key={c.key} value={c.key}>{c.name}</option>
							))}
						</select>
					</li>
					<li className="crsg-sf-formats">
						<label for="stations-formats">
							Formats:
						</label>
						<select
							name="format"
							id="stations-formats"
							value={filters.format}
							onChange={changeFormatFilter}
						>
							<option key="all" value="all">All</option>
							{filteredData.formats.map(f => (
								<option key={f} value={f}>{f}</option>
							))}
						</select>
					</li>
					<li className="crsg-sf-search">
						<label for="stations-search">Search:</label>
						<input
							name="search"
							id="stations-search"
							type="text"
							placeHolder="Search..."
							value={filters.query}
							ariaLabel="Search"
							spellCheck={false}
							onKeyUp={debounceQuery}
						/>
						<button
							ariaLabel="Clear Search"
							onClick={clearQuery}
						>
							Clear
						</button>
					</li>
				</ul>
				<ul className="crsg-sf-stations">
					{!!filteredStations.length &&
						filteredStations.map(station => (
							<li>
								<Station {...station} />
							</li>
						))
					}
					{!!filteredStations.length ||
						<li>No stations found.</li>
					}
				</ul>
			</div>
		)
	}
}
